CREATE TABLE IF NOT EXISTS products (
    id BIGSERIAL PRIMARY KEY ,
    name VARCHAR(150) UNIQUE ,
    price VARCHAR(50) NOT NULL ,
    category VARCHAR(150) NOT NULL ,
    image BYTEA NOT NULL
    ); 
